#==========================  Modules configuration =============================
filebeat.modules:

filebeat.autodiscover:
  providers:
  - type: docker
    templates:
        - condition:
            contains:
              docker.container.image: java-ms
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              processors:
              #- add_docker_metadata: ~
              json.keys_under_root: false
              json.add_error_key: true


#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "my_login"
  password: "my_password"

xpack.monitoring:
  enabled: true
  elasticsearch:

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true
setup.kibana:
  host: "kibana:5601"
  username: "my_login"
  password: "my_password"