#==========================  Modules configuration =============================
filebeat.modules:


#========================== Filebeat autodiscover ==============================
# Autodiscover allows you to detect changes in the system and spawn new modules or inputs as they happen.
filebeat.autodiscover:
  # Autodiscover docker containers and parse logs
  providers:
  - type: docker
    templates:
      config:
      - type: docker
        containers.ids:
        - "${data.docker.container.id}"

#=========================== Filebeat inputs ==============================
filebeat.inputs:
#------------------------------ Docker input --------------------------------
- type: docker
  enabled: true
  containers.ids:
  - "*"
  paths:
  - /var/lib/docker/containers/${data.docker.container.id}/*.log
  json.message_key: log
  json.add_error_key: true
  json.keys_under_root: true

  exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
  multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
  multiline.match: after
  processors:
  - decode_json_fields:
      fields: ["log"]
      target: ""
      # overwrite existing target elasticsearch fields while decoding json fields
      overwrite_keys: true
  - add_docker_metadata: ~
  - add_cloud_metadata: ~
  - add_locale: ~

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "my_login"
  password: "my_password"

xpack.monitoring:
  enabled: true
  elasticsearch:

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true
setup.kibana:
  host: "kibana:5601"
  username: "my_login"
  password: "my_password"