version: "3.6"
services:

  javamicroservice:
    build:
      context: ./..
      args:
      - JAR_FILE=./build/libs/javamicroservice.jar
    ports:
    - "8080:8080"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.1
    container_name: filebeat
    user: root
    volumes:
    - "./filebeat/file.yml:/usr/share/filebeat/filebeat.yml"
    - "/var/lib/docker/containers/:/var/lib/docker/containers/:ro"
    - "/var/run/docker.sock:/var/run/docker.sock"
